# Generated by Django 5.0.1 on 2024-02-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to="profile_pics"
            ),
        ),
    ]
