# Generated by Django 5.0.1 on 2024-03-25 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_bookmarks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bookmarks",
        ),
    ]
