# Generated by Django 5.0.1 on 2024-04-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_profile_bookmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
