# Generated by Django 5.0.1 on 2024-04-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(max_length=50),
        ),
    ]
