# Generated by Django 5.0.1 on 2024-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_profile_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(blank=True, to="accounts.profile"),
        ),
    ]
