# Generated by Django 5.0.1 on 2024-04-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="accounts.profile"
            ),
        ),
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
