# Generated by Django 5.0.1 on 2024-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_profile_following_delete_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_name",
            field=models.CharField(max_length=20),
        ),
    ]
