# Generated by Django 5.0.1 on 2024-02-21 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postcomments",
            options={"verbose_name_plural": "comments"},
        ),
    ]
