# Generated by Django 5.0.1 on 2024-02-22 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_postcomments_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostComments",
            new_name="Comment",
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
    ]
