# Generated by Django 5.0.1 on 2024-02-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_comment_is_flagged_comment_parent_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_content",
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_content",
            field=models.TextField(max_length=350),
        ),
    ]
