# Generated by Django 5.0.1 on 2024-03-21 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_comment_comment_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_content",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_likes",
            new_name="likes",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_media",
            new_name="media",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="post_content",
            new_name="content",
        ),
    ]
