# Generated by Django 5.0.1 on 2024-03-21 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_rename_comment_content_comment_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post_key",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
