# Generated by Django 5.0.1 on 2024-03-21 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_comment_post_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
