# Generated by Django 5.0.1 on 2024-03-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_rename_content_post_post_content_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_reply",
            field=models.BooleanField(default=False),
        ),
    ]
