# Generated by Django 5.0.1 on 2024-03-25 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_post_is_reply"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bookmarked_by",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
