# Generated by Django 5.0.1 on 2024-03-25 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_post_bookmarked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="bookmarked_by",
        ),
    ]
