# Generated by Django 5.0.1 on 2024-03-28 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_post_bookmarked"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bookmark",
        ),
    ]
