# Generated by Django 5.0.1 on 2024-03-28 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0017_delete_bookmark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="bookmarked",
            new_name="bookmarks",
        ),
    ]
