# Generated by Django 5.0.1 on 2024-04-16 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0020_post_reposted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="reposted_by",
            field=models.ManyToManyField(
                blank=True, related_name="reposts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
