# Generated by Django 5.0.1 on 2024-04-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0022_repost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="repost",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="repost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposts",
                to="posts.post",
            ),
        ),
    ]
