# Generated by Django 5.0.1 on 2024-04-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0023_alter_post_options_alter_repost_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reposts",
                to="posts.post",
            ),
        ),
    ]
