# Generated by Django 5.0.1 on 2024-04-17 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0024_alter_repost_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repost",
            options={"ordering": ["-repost_datetime"]},
        ),
        migrations.RenameField(
            model_name="repost",
            old_name="date",
            new_name="repost_datetime",
        ),
        migrations.RemoveField(
            model_name="post",
            name="reposted_by",
        ),
    ]
