# Generated by Django 5.0.1 on 2024-04-17 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0025_alter_repost_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-datetime"]},
        ),
        migrations.AlterModelOptions(
            name="repost",
            options={"ordering": ["-datetime"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="date",
            new_name="datetime",
        ),
        migrations.RenameField(
            model_name="repost",
            old_name="repost_datetime",
            new_name="datetime",
        ),
    ]
