# Generated by Django 5.0.1 on 2024-04-17 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0026_alter_post_options_alter_repost_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reposted_by",
            field=models.ManyToManyField(
                blank=True, related_name="reposts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
