# Generated by Django 5.0.1 on 2024-04-29 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0030_notification_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="receiver",
        ),
    ]
