# Generated by Django 5.0.1 on 2024-04-29 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0033_notification_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
