# Generated by Django 5.0.1 on 2024-04-30 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0035_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="post",
            new_name="receiver",
        ),
        migrations.AddField(
            model_name="notification",
            name="post_creator",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
            ),
        ),
    ]
