# Generated by Django 5.0.1 on 2024-05-10 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0036_rename_post_notification_receiver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="reposted_by",
        ),
    ]
