# Generated by Django 5.0.1 on 2024-05-10 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0037_remove_post_reposted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reposted_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="reposts",
                through="posts.Repost",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
