# Generated by Django 5.0.1 on 2024-05-10 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0038_post_reposted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="bookmarks",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
