# Generated by Django 5.0.1 on 2024-05-10 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0040_alter_repost_post_alter_repost_user_bookmark_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bookmarks",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_bookmarks",
                through="posts.Bookmark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_likes",
                through="posts.Like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
