# Generated by Django 5.0.1 on 2024-05-10 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0041_post_bookmarks_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_flagged",
        ),
    ]
