# Generated by Django 5.0.1 on 2024-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0042_remove_post_is_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="modified",
            field=models.BooleanField(default=False),
        ),
    ]
